// Dev-only generator: extracts the AAC Huffman and band tables (ISO/IEC
// 14496-3 data) from an FFmpeg aactab.c and writes
// lib/core/codec/audio/aac_tables.dart.
//
// Usage (from app/):
//   dart run tool/audio/gen_aac_tables.dart <path/to/aactab.c>
import 'dart:io';

List<int> _array(String src, String name) {
  final re = RegExp(
    r'\b' + RegExp.escape(name) + r'\s*\[[^\]]*\]\s*=\s*\{([^}]*)\}',
  );
  final m = re.firstMatch(src);
  if (m == null) throw StateError('table $name not found');
  final body = m.group(1)!.replaceAll(RegExp(r'/\*.*?\*/', dotAll: true), '');
  return body
      .split(',')
      .map((s) => s.trim())
      .where((s) => s.isNotEmpty)
      .map(
        (s) => s.startsWith('0x')
            ? int.parse(s.substring(2), radix: 16)
            : int.parse(s),
      )
      .toList();
}

String _fmt(String name, List<int> v, {bool hex = false}) {
  final rows = <String>[];
  for (var i = 0; i < v.length; i += 12) {
    final row = v.sublist(i, i + 12 > v.length ? v.length : i + 12);
    rows.add('  ${row.map((x) => hex ? '0x${x.toRadixString(16)}' : '$x').join(', ')}');
  }
  return 'const List<int> $name = [\n${rows.join(',\n')}\n];\n';
}

void main(List<String> args) {
  final src = File(args[0]).readAsStringSync();
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/audio/gen_aac_tables.dart. Do not edit.')
    ..writeln(
      '// AAC tables from ISO/IEC 14496-3 (Huffman codebooks, scalefactor',
    )
    ..writeln('// band offsets, TNS limits).')
    ..writeln();
  out.write(
    _fmt(
      'aacScalefactorCodes',
      _array(src, 'ff_aac_scalefactor_code'),
      hex: true,
    ),
  );
  out.write(_fmt('aacScalefactorBits', _array(src, 'ff_aac_scalefactor_bits')));
  final codes = <String>[], bits = <String>[];
  for (var i = 1; i <= 11; i++) {
    out.write(_fmt('_codes$i', _array(src, 'codes$i'), hex: true));
    out.write(_fmt('_bits$i', _array(src, 'bits$i')));
    codes.add('_codes$i');
    bits.add('_bits$i');
  }
  out.writeln(
    'const List<List<int>> aacSpectralCodes = [${codes.join(', ')}];',
  );
  out.writeln('const List<List<int>> aacSpectralBits = [${bits.join(', ')}];');
  out.writeln();
  for (final n in ['96', '64', '48', '32', '24', '16', '8']) {
    out.write(_fmt('_swb1024_$n', _array(src, 'swb_offset_1024_$n')));
  }
  for (final n in ['96', '48', '24', '16', '8']) {
    out.write(_fmt('_swb128_$n', _array(src, 'swb_offset_128_$n')));
  }
  out.writeln(
    '/// Long window band offsets indexed by sampling frequency index.',
  );
  out.writeln(
    'const List<List<int>> aacSwbOffset1024 = [_swb1024_96, _swb1024_96, _swb1024_64, '
    '_swb1024_48, _swb1024_48, _swb1024_32, _swb1024_24, _swb1024_24, _swb1024_16, '
    '_swb1024_16, _swb1024_16, _swb1024_8, _swb1024_8];',
  );
  out.writeln(
    '/// Short window band offsets indexed by sampling frequency index.',
  );
  out.writeln(
    'const List<List<int>> aacSwbOffset128 = [_swb128_96, _swb128_96, _swb128_96, '
    '_swb128_48, _swb128_48, _swb128_48, _swb128_24, _swb128_24, _swb128_16, '
    '_swb128_16, _swb128_16, _swb128_8, _swb128_8];',
  );
  out.write(_fmt('aacNumSwb1024', _array(src, 'ff_aac_num_swb_1024')));
  out.write(_fmt('aacNumSwb128', _array(src, 'ff_aac_num_swb_128')));
  out.write(_fmt('aacTnsMaxBands1024', _array(src, 'ff_tns_max_bands_1024')));
  out.write(_fmt('aacTnsMaxBands128', _array(src, 'ff_tns_max_bands_128')));
  File('lib/core/codec/audio/aac_tables.dart')
      .writeAsStringSync(out.toString());
}
