// Generates lib/core/dvb/ldpc_tables.dart from host/dvbs2_ldpc.json.
// Run from app/: dart run tool/gen_ldpc.dart
import 'dart:convert';
import 'dart:io';

void main() {
  final j = jsonDecode(File('../host/dvbs2_ldpc.json').readAsStringSync()) as Map<String, dynamic>;
  final b = StringBuffer()
    ..writeln('// GENERATED by tool/gen_ldpc.dart from host/dvbs2_ldpc.json. Do not edit.')
    ..writeln('// DVB-S2 LDPC parity address tables (EN 302 307 annex B and C): for every group')
    ..writeln('// of 360 information bits, the parity addresses it is added to.')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln('const Map<String, Map<String, List<List<int>>>> ldpcTables = {');
  for (final frame in j.keys) {
    b.writeln("  '$frame': {");
    final m = j[frame] as Map<String, dynamic>;
    for (final fec in m.keys) {
      b.writeln("    '$fec': [");
      for (final row in m[fec] as List) {
        b.writeln('      [${(row as List).join(', ')}],');
      }
      b.writeln('    ],');
    }
    b.writeln('  },');
  }
  b.writeln('};');
  File('lib/core/dvb/ldpc_tables.dart').writeAsStringSync(b.toString());
}
